"""
Audit Log Service

Centralized service for emitting audit log entries.
Keeps audit logging simple and consistent across the application.
"""
import uuid
from datetime import datetime, timezone
from typing import Optional, Dict, Any

from core.database import db


async def emit_audit_log(
    event_type: str,
    actor_type: str = "system",
    actor_id: Optional[str] = None,
    actor_email: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
    description: Optional[str] = None
):
    """
    Emit an audit log entry.
    
    Args:
        event_type: Type of event (e.g., "user.signup", "agent.created")
        actor_type: Who performed the action ("user", "admin", "system")
        actor_id: ID of the actor (None for system events)
        actor_email: Email of the actor (for display purposes)
        metadata: Additional context as JSON-serializable dict
        description: Human-readable description of the event
    """
    log_entry = {
        "id": str(uuid.uuid4()),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "actor_type": actor_type,
        "actor_id": actor_id,
        "actor_email": actor_email,
        "event_type": event_type,
        "metadata": metadata or {},
        "description": description
    }
    
    await db.audit_logs.insert_one(log_entry)
    return log_entry


# Convenience functions for common events

async def log_user_signup(user_id: str, email: str):
    """Log a user signup event"""
    await emit_audit_log(
        event_type="user.signup",
        actor_type="user",
        actor_id=user_id,
        actor_email=email,
        metadata={"user_id": user_id, "email": email},
        description=f"New user signed up: {email}"
    )


async def log_user_login(user_id: str, email: str):
    """Log a user login event"""
    await emit_audit_log(
        event_type="user.login",
        actor_type="user",
        actor_id=user_id,
        actor_email=email,
        metadata={"user_id": user_id},
        description=f"User logged in: {email}"
    )


async def log_api_key_created(user_id: str, email: str, key_id: str):
    """Log API key creation (during signup)"""
    await emit_audit_log(
        event_type="api_key.created",
        actor_type="system",
        actor_id=None,
        actor_email=None,
        metadata={"user_id": user_id, "key_id": key_id, "email": email},
        description=f"API key created for {email}"
    )


async def log_api_key_regenerated(user_id: str, email: str, key_id: str):
    """Log API key regeneration"""
    await emit_audit_log(
        event_type="api_key.regenerated",
        actor_type="user",
        actor_id=user_id,
        actor_email=email,
        metadata={"user_id": user_id, "key_id": key_id},
        description=f"API key regenerated by {email}"
    )


async def log_agent_created(user_id: str, email: str, agent_id: str, agent_name: str):
    """Log agent creation"""
    await emit_audit_log(
        event_type="agent.created",
        actor_type="user",
        actor_id=user_id,
        actor_email=email,
        metadata={"agent_id": agent_id, "agent_name": agent_name},
        description=f"Agent created: {agent_name}"
    )


async def log_outcome_created(
    user_id: str, 
    email: str, 
    agent_id: str, 
    outcome_id: str, 
    result: str,
    submitter_type: str = "self"
):
    """Log outcome submission"""
    actor_type = "user" if submitter_type == "self" else "system"
    await emit_audit_log(
        event_type="outcome.logged",
        actor_type=actor_type,
        actor_id=user_id,
        actor_email=email,
        metadata={
            "agent_id": agent_id,
            "outcome_id": outcome_id,
            "result": result,
            "submitter_type": submitter_type
        },
        description=f"Outcome logged: {result} for agent {agent_id[:8]}..."
    )


async def log_agent_flagged(
    user_id: str, 
    email: str, 
    agent_id: str, 
    flag_id: str, 
    reason: str,
    outcome_id: Optional[str] = None
):
    """Log agent/outcome flagging"""
    target = f"outcome {outcome_id[:8]}..." if outcome_id else f"agent {agent_id[:8]}..."
    await emit_audit_log(
        event_type="agent.flagged",
        actor_type="user",
        actor_id=user_id,
        actor_email=email,
        metadata={
            "agent_id": agent_id,
            "flag_id": flag_id,
            "outcome_id": outcome_id,
            "reason": reason
        },
        description=f"Flag created on {target}: {reason}"
    )


async def log_agent_public_toggled(
    user_id: str,
    email: str,
    agent_id: str,
    agent_name: str,
    is_public: bool
):
    """Log agent public visibility toggle"""
    status = "public" if is_public else "private"
    await emit_audit_log(
        event_type="agent.public_toggled",
        actor_type="user",
        actor_id=user_id,
        actor_email=email,
        metadata={
            "agent_id": agent_id,
            "agent_name": agent_name,
            "is_public": is_public
        },
        description=f"Agent '{agent_name}' set to {status}"
    )
